logging:
  level:
    org.springframework.web: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.org.linkedin: DEBUG

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

apiPrefix: /js

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: job-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URI:jdbc:postgresql://localhost:5432/job_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/linkedin
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        max.block.ms: 2000
    consumer:
      group-id: job-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.org.linkedin.dto.event"

kafka:
  topics:
    user-deleted: user-deleted

openapi:
  service:
    title: job-service doc
    version: 1.0.0
    url: ${OPENAPI_URL:http://localhost:9191/js}
