server:
  port: 9095

apiPrefix: /ns

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URI:jdbc:postgresql://localhost:5432/notification_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.org.linkedin.dto.event"

openapi:
  service:
    title: notification-service doc
    version: 1.0.0
    url: ${OPENAPI_URL:http://localhost:9191/ns}

kafka:
  topics:
    connection-requested: connection-requested
    connection-accepted: connection-accepted
    post-liked: post-liked
    comment-created: comment-created
    profile-viewed: profile-viewed
