package com.org.linkedin.user.utility;

import java.text.MessageFormat;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpHeaders;
import org.springframework.web.util.UriComponentsBuilder;

/**
 * Utility class for handling pagination.
 *
 * <p>Pagination uses the same principles as the <a
 * href="https://developer.github.com/v3/#pagination">GitHub API</a>, and follow <a
 * href="http://tools.ietf.org/html/rfc5988">RFC 5988 (Link header)</a>.
 */
public final class PaginationUtil {

  private static final String HEADER_X_TOTAL_COUNT = "X-Total-Count";
  private static final String HEADER_LINK_FORMAT = "<{0}>; rel=\"{1}\"";

  private PaginationUtil() {}

  /**
   * Generate pagination headers for a Spring Data {@link Page} object.
   *
   * @param uriBuilder The URI builder.
   * @param page The page.
   * @param <T> The type of object.
   * @return http header.
   */
  public static <T> HttpHeaders generatePaginationHttpHeaders(
      UriComponentsBuilder uriBuilder, Page<T> page) {
    HttpHeaders headers = new HttpHeaders();
    headers.add(HEADER_X_TOTAL_COUNT, Long.toString(page.getTotalElements()));
    int pageNumber = page.getNumber();
    int pageSize = page.getSize();
    StringBuilder link = new StringBuilder();
    if (pageNumber < page.getTotalPages() - 1) {
      link.append(prepareLink(uriBuilder, pageNumber + 1, pageSize, "next")).append(",");
    }
    if (pageNumber > 0) {
      link.append(prepareLink(uriBuilder, pageNumber - 1, pageSize, "prev")).append(",");
    }
    link.append(prepareLink(uriBuilder, page.getTotalPages() - 1, pageSize, "last"))
        .append(",")
        .append(prepareLink(uriBuilder, 0, pageSize, "first"));
    headers.add(HttpHeaders.LINK, link.toString());
    return headers;
  }

  /**
   * Prepares a link header string with the specified page number, page size, and relation type.
   *
   * <p>This method constructs a link header string using a URI prepared with pagination parameters
   * (page number and page size) and a relation type. The URI is generated by the {@link
   * #preparePageUri} method, and the link header string is formatted according to the {@code
   * HEADER_LINK_FORMAT}.
   *
   * @param uriBuilder the {@link UriComponentsBuilder} used to build the base URI
   * @param pageNumber the page number to set in the "page" query parameter of the URI
   * @param pageSize the page size to set in the "size" query parameter of the URI
   * @param relType the relation type to be included in the link header (e.g., "next", "prev")
   * @return the formatted link header string
   */
  private static String prepareLink(
      UriComponentsBuilder uriBuilder, int pageNumber, int pageSize, String relType) {
    return MessageFormat.format(
        HEADER_LINK_FORMAT, preparePageUri(uriBuilder, pageNumber, pageSize), relType);
  }

  /**
   * Prepares a URI string with the specified page number and page size.
   *
   * <p>This method uses a {@link UriComponentsBuilder} to modify the query parameters of a URI,
   * setting the "page" parameter to the specified page number and the "size" parameter to the
   * specified page size. The resulting URI string will have commas (",") replaced with "%2C" and
   * semicolons (";") replaced with "%3B" to ensure proper encoding.
   *
   * @param uriBuilder the {@link UriComponentsBuilder} used to build the URI
   * @param pageNumber the page number to set in the "page" query parameter
   * @param pageSize the page size to set in the "size" query parameter
   * @return the prepared URI string with the specified page number and page size
   */
  private static String preparePageUri(
      UriComponentsBuilder uriBuilder, int pageNumber, int pageSize) {
    return uriBuilder
        .replaceQueryParam("page", Integer.toString(pageNumber))
        .replaceQueryParam("size", Integer.toString(pageSize))
        .toUriString()
        .replace(",", "%2C")
        .replace(";", "%3B");
  }
}
