version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linkedin-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - linkedin-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - linkedin-network

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - linkedin-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      - discovery-service
    networks:
      - linkedin-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on:
      - postgres
      - kafka
      - discovery-service
    networks:
      - linkedin-network

  profile-service:
    build:
      context: .
      dockerfile: profile-service/Dockerfile
    depends_on:
      - postgres
      - kafka
      - discovery-service
    networks:
      - linkedin-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - kafka
      - discovery-service
    networks:
      - linkedin-network

  job-service:
    build:
      context: .
      dockerfile: job-service/Dockerfile
    depends_on:
      - postgres
      - kafka
      - discovery-service
    networks:
      - linkedin-network

  chat-service:
    build:
      context: .
      dockerfile: chat-service/Dockerfile
    depends_on:
      - postgres
      - kafka
      - discovery-service
    networks:
      - linkedin-network

networks:
  linkedin-network:

volumes:
  postgres_data:
