logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG

server:
  port: 9191

spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/linkedin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/ps/**
          filters:
            - name: CircuitBreaker
              args:
                name: profileServiceCB
                fallbackUri: forward:/fallback/profile
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/us/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/ns/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                fallbackUri: forward:/fallback/notification
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/js/**
          filters:
            - name: CircuitBreaker
              args:
                name: jobServiceCB
                fallbackUri: forward:/fallback/job
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/cs/**
          filters:
            - name: CircuitBreaker
              args:
                name: chatServiceCB
                fallbackUri: forward:/fallback/chat
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/ss/**
          filters:
            - name: CircuitBreaker
              args:
                name: searchServiceCB
                fallbackUri: forward:/fallback/search
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT

        - id: chat-service-ws
          uri: lb://chat-service
          predicates:
            - Path=/ws-chat/**

        - id: notification-service-ws
          uri: lb://notification-service
          predicates:
            - Path=/ws-notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      profileServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        timeoutDuration: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      userServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        timeoutDuration: 20s
      notificationServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      jobServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      chatServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      searchServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  timelimiter:
    instances:
      profileServiceCB:
        timeoutDuration: 10s
      userServiceCB:
        timeoutDuration: 30s
      notificationServiceCB:
        timeoutDuration: 3s
      jobServiceCB:
        timeoutDuration: 3s
      chatServiceCB:
        timeoutDuration: 3s
      searchServiceCB:
        timeoutDuration: 10s

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: User Service
        url: /us/v3/api-docs
      - name: Notification Service
        url: /ns/v3/api-docs
