server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

apiPrefix: /ss

spring:
  application:
    name: search-service
  
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    socket-timeout: 10s
    connection-timeout: 5s
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/linkedin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.org.linkedin.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.security: DEBUG
