server:
  port: 8700

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

apiPrefix: /ps

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

openapi:
  service:
    title: profile-service doc
    version: 1.0.0
    url: ${OPENAPI_URL:http://localhost:9191/ps}

spring:
  application:
    name: profile-service
  main:
    allow-bean-definition-overriding: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URI:jdbc:postgresql://localhost:5432/profile_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      poolName: Hikari
      maximumPoolSize: 5
      minimumIdle: 2
      idleTimeout: 300000
      autoCommit: false
      maxLifetime: 600000
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/linkedin
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        max.block.ms: 2000
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.org.linkedin.dto.event"

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:admin}
    secret-key: ${AWS_S3_SECRET_KEY:password}
    region: ${AWS_S3_REGION:us-east-1}
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
    bucket: ${AWS_S3_BUCKET:linkedin-uploads}
    public-url: ${AWS_S3_PUBLIC_URL:http://localhost:9000}

kafka:
  topics:
    post-created: post-created
    post-reacted: post-reacted
    comment-created: comment-created
    profile-viewed: profile-viewed
    connection-requested: connection-requested
    connection-accepted: connection-accepted
