package com.org.linkedin.utility.errors;

public interface ErrorKeys {

  String SERVICE_NOT_AVAILABLE = "SERVICE_NOT_AVAILABLE";
  String INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY";
  String SYSTEM_ERROR = "SYSTEM_ERROR";
  String INVALID_ID = "INVALID_ID";
  String ID_NOT_FOUND = "ID_NOT_FOUND";

  String ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND";
  String PASSWORD_AND_CONFIRM_PASSWORD_DO_NOT_MATCH = "PASSWORD_AND_CONFIRM_PASSWORD_DO_NOT_MATCH";
  String INVALID_REQUEST = "INVALID_REQUEST";
  String NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND";
  String USER_NOT_FOUND = "USER_NOT_FOUND";
  String USER_INACTIVE = "USER_INACTIVE";
  String NO_USER_FOUND_FOR_SEND_NOTIFICATION = "NO_USER_FOUND_FOR_SEND_NOTIFICATION";
  String INVALID_USER_CREDENTIALS = "INVALID_USER_CREDENTIALS";
  String ACCESS_DENIED = "ACCESS_DENIED";
  String INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN";
  String USER_ALREADY_EXISTS_WITH_THIS_EMAIL = "USER_ALREADY_EXISTS_WITH_THIS_EMAIL";
  String INVALID_ROLE = "INVALID_ROLE";
  String ROLE_DOES_NOT_EXIST = "ROLE_DOES_NOT_EXIST";
  String ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS";
  String INVALID_ROLE_ID = "INVALID_ROLE_ID";
  String UNABLE_TO_CREATE_USER = "UNABLE_TO_CREATE_USER";
  String ERROR_ENABLING_USER = "ERROR_ENABLING_USER";
  String ERROR_DISABLING_USER = "ERROR_DISABLING_USER";
  String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
  String SCOPE_NOT_FOUND = "SCOPE_NOT_FOUND";
  String PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND";
  String PERMISSION_EXISTS_WITH_SAME_NAME = "PERMISSION_EXISTS_WITH_SAME_NAME";
  String FILE_NOT_FOUND = "FILE_NOT_FOUND";
  String STORAGE_ALREADY_EXIST_WITH_NAME_OR_CODE = "STORAGE_ALREADY_EXIST_WITH_NAME_OR_CODE";
  String DATA_NOT_FOUND = "DATA_NOT_FOUND";
  String INVALID_USER = "INVALID_USER";
  String INVALID_TOKEN_FORMAT = "INVALID_TOKEN_FORMAT";
  String FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED";
  String INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT";
}
