server:
  port: 8086

apiPrefix: /cs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: chat-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URI:jdbc:postgresql://localhost:5432/chat_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/linkedin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

openapi:
  service:
    title: chat-service doc
    version: 1.0.0
    url: ${OPENAPI_URL:http://localhost:9191/cs}
